package com.mavenforum.model.entity;

public class Tminfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tminfo.userid
     *
     * @mbg.generated Tue Sep 29 12:49:06 CST 2020
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tminfo.logintm
     *
     * @mbg.generated Tue Sep 29 12:49:06 CST 2020
     */
    private String logintm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tminfo.userid
     *
     * @return the value of tminfo.userid
     *
     * @mbg.generated Tue Sep 29 12:49:06 CST 2020
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tminfo.userid
     *
     * @param userid the value for tminfo.userid
     *
     * @mbg.generated Tue Sep 29 12:49:06 CST 2020
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tminfo.logintm
     *
     * @return the value of tminfo.logintm
     *
     * @mbg.generated Tue Sep 29 12:49:06 CST 2020
     */
    public String getLogintm() {
        return logintm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tminfo.logintm
     *
     * @param logintm the value for tminfo.logintm
     *
     * @mbg.generated Tue Sep 29 12:49:06 CST 2020
     */
    public void setLogintm(String logintm) {
        this.logintm = logintm == null ? null : logintm.trim();
    }

	@Override
	public String toString() {
		return "Tminfo [userid=" + userid + ", logintm=" + logintm + "]";
	}

	public Tminfo(String userid, String logintm) {
		super();
		this.userid = userid;
		this.logintm = logintm;
	}

	public Tminfo() {
		super();
		// TODO Auto-generated constructor stub
	}
}