package com.mavenforum.model.entity;

public class Userinfo {
    @Override
	public String toString() {
		return "Userinfo [userid=" + userid + ", userpwd=" + userpwd + ", email=" + email + "]";
	}

	public Userinfo(String userid, String userpwd, String email) {
		super();
		this.userid = userid;
		this.userpwd = userpwd;
		this.email = email;
	}

	public Userinfo() {
		super();
		// TODO Auto-generated constructor stub
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userid
     *
     * @mbg.generated Tue Sep 22 13:11:18 CST 2020
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userpwd
     *
     * @mbg.generated Tue Sep 22 13:11:18 CST 2020
     */
    private String userpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.email
     *
     * @mbg.generated Tue Sep 22 13:11:18 CST 2020
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userid
     *
     * @return the value of userinfo.userid
     *
     * @mbg.generated Tue Sep 22 13:11:18 CST 2020
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userid
     *
     * @param userid the value for userinfo.userid
     *
     * @mbg.generated Tue Sep 22 13:11:18 CST 2020
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userpwd
     *
     * @return the value of userinfo.userpwd
     *
     * @mbg.generated Tue Sep 22 13:11:18 CST 2020
     */
    public String getUserpwd() {
        return userpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userpwd
     *
     * @param userpwd the value for userinfo.userpwd
     *
     * @mbg.generated Tue Sep 22 13:11:18 CST 2020
     */
    public void setUserpwd(String userpwd) {
        this.userpwd = userpwd == null ? null : userpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.email
     *
     * @return the value of userinfo.email
     *
     * @mbg.generated Tue Sep 22 13:11:18 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.email
     *
     * @param email the value for userinfo.email
     *
     * @mbg.generated Tue Sep 22 13:11:18 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}