package com.mavenforum.model.dao;

import com.mavenforum.model.entity.Admininfo;
import com.mavenforum.model.entity.AdmininfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdmininfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admininfo
     *
     * @mbg.generated Tue Sep 29 21:01:05 CST 2020
     */
    long countByExample(AdmininfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admininfo
     *
     * @mbg.generated Tue Sep 29 21:01:05 CST 2020
     */
    int deleteByExample(AdmininfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admininfo
     *
     * @mbg.generated Tue Sep 29 21:01:05 CST 2020
     */
    int deleteByPrimaryKey(String adminid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admininfo
     *
     * @mbg.generated Tue Sep 29 21:01:05 CST 2020
     */
    int insert(Admininfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admininfo
     *
     * @mbg.generated Tue Sep 29 21:01:05 CST 2020
     */
    int insertSelective(Admininfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admininfo
     *
     * @mbg.generated Tue Sep 29 21:01:05 CST 2020
     */
    List<Admininfo> selectByExample(AdmininfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admininfo
     *
     * @mbg.generated Tue Sep 29 21:01:05 CST 2020
     */
    Admininfo selectByPrimaryKey(String adminid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admininfo
     *
     * @mbg.generated Tue Sep 29 21:01:05 CST 2020
     */
    int updateByExampleSelective(@Param("record") Admininfo record, @Param("example") AdmininfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admininfo
     *
     * @mbg.generated Tue Sep 29 21:01:05 CST 2020
     */
    int updateByExample(@Param("record") Admininfo record, @Param("example") AdmininfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admininfo
     *
     * @mbg.generated Tue Sep 29 21:01:05 CST 2020
     */
    int updateByPrimaryKeySelective(Admininfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admininfo
     *
     * @mbg.generated Tue Sep 29 21:01:05 CST 2020
     */
    int updateByPrimaryKey(Admininfo record);
}