package com.mavenforum.model.dao;

import com.mavenforum.model.entity.Tminfo;
import com.mavenforum.model.entity.TminfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TminfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tminfo
     *
     * @mbg.generated Tue Sep 29 12:49:06 CST 2020
     */
    long countByExample(TminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tminfo
     *
     * @mbg.generated Tue Sep 29 12:49:06 CST 2020
     */
    int deleteByExample(TminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tminfo
     *
     * @mbg.generated Tue Sep 29 12:49:06 CST 2020
     */
    int insert(Tminfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tminfo
     *
     * @mbg.generated Tue Sep 29 12:49:06 CST 2020
     */
    int insertSelective(Tminfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tminfo
     *
     * @mbg.generated Tue Sep 29 12:49:06 CST 2020
     */
    List<Tminfo> selectByExample(TminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tminfo
     *
     * @mbg.generated Tue Sep 29 12:49:06 CST 2020
     */
    int updateByExampleSelective(@Param("record") Tminfo record, @Param("example") TminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tminfo
     *
     * @mbg.generated Tue Sep 29 12:49:06 CST 2020
     */
    int updateByExample(@Param("record") Tminfo record, @Param("example") TminfoExample example);
}